In [5]:
import numpy as np
import pandas as pd
from pandas import DataFrame
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score as ass

#read values
y_train = pd.read_csv("B_y_train.csv",delimiter=",")
y_test = pd.read_csv("B_y_test.csv",delimiter=",")
x_train = pd.read_csv("B_X_train.csv",delimiter=",")
x_test = pd.read_csv("B_X_test.csv",delimiter=",")
#Clean Values
x_train.pop('Unnamed: 0')
x_test.pop('Unnamed: 0')
y_train.pop('Unnamed: 0')
y_test.pop('Unnamed: 0')
#Feature Engineering
x_train['volbr'] = (x_train['Breite']*x_train['Volumen'])
x_train['volho'] = (x_train['Hoehe']*x_train['Volumen'])
x_test['volbr'] = (x_test['Breite']*x_test['Volumen'])
x_test['volho'] = (x_test['Hoehe']*x_test['Volumen'])

In [6]:
le = preprocessing.LabelEncoder()
y_train_df = DataFrame()
y_test_df = DataFrame()
y_train_df=le.fit_transform(y_train)
y_test_df =le.fit_transform(y_test)

scaler_test = preprocessing.StandardScaler()
scaled_df_train = scaler_test.fit_transform(x_train)
scaled_x_train = pd.DataFrame(scaled_df_train)
scaled_df_test = scaler_test.fit_transform(x_test)
scaled_x_test = pd.DataFrame(scaled_df_test)

C:\Users\Lukas\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
regr = LogisticRegression(penalty='elasticnet',multi_class='multinomial',solver='saga',max_iter=10000)
regr.fit(scaled_x_train, y_train_df)
resultData = regr.predict (scaled_x_test)
result_df = DataFrame(resultData)
orig_df = DataFrame(y_test_df)

print("Accuracy: " +str(ass(orig_df,result_df)))
print(confusion_matrix(result_df,y_test_df))

Accuracy: 0.47878787878787876
[[65 57  5 12]
 [10 16  2  0]
 [ 3  5 62 48]
 [ 8 14  8 15]]
